"""empty message

Revision ID: 8fdda8e694d9
Revises: beeee59a4171
Create Date: 2024-02-22 15:35:26.517651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fdda8e694d9'
down_revision = 'beeee59a4171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enclosure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeding',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('enclosure_id', sa.Integer(), nullable=False),
    sa.Column('time', sa.String(length=20), nullable=False),
    sa.Column('food', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.id'], ),
    sa.ForeignKeyConstraint(['enclosure_id'], ['enclosure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feeding')
    op.drop_table('enclosure')
    # ### end Alembic commands ###
